apiVersion: v1
kind: Service
metadata:
  name: xrfcapiref
  namespace: xrf
spec:
  selector:
    app: xrfcapiref
  type: ClusterIP
  ports:
    - name: http
      port: 9095
      targetPort: 9095
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrfcref
  namespace: xrf
  labels:
    app: xrfcref
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xrfcref
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: xrf-ext-netref
              #config.linkerd.io/enable-debug-sidecar: "true"
              #linkerd.io/inject: enabled
      labels:
        app: xrfcref
    spec:
      containers:
      - name: xrfc
        image: tolgaomeratalay/xrfclient:recvclientv4 #4.2
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVER_XRF
          value: "20.12.10.10"
        - name: XRF_PORT
          value: "9090"
        - name: SERVER_CLIENT
          value: "20.12.10.30"
        - name: CLIENT_PORT
          value: "9095"
        - name: REG_COUNT
          value: "1"
        - name: CLIENT_COUNT
          value: "5"
        - name: METHOD
          value: "1"

